### ISSUE TITLE
How to handle navigationDelegate of webView object.

### ISSUE THREAD

**Issue by kythanh** [kylehickinson/SwiftUI-WebView#7]
Hi @kylehickinson 
Do you have any idea how to handle navigationDelegate of webView object. Below are one of delegate I would like to handle with the webView object. Thank you.

```
public func webView(_ webView: WKWebView, didReceive challenge: URLAuthenticationChallenge, completionHandler: @escaping (URLSession.AuthChallengeDisposition, URLCredential?) -> Void) {
            if challenge.protectionSpace.host == "correcturl.com" {
                let user = "user"
                let password = "password"
                let credential = URLCredential(user: user, password: password, persistence: URLCredential.Persistence.forSession)
                challenge.sender?.use(credential, for: challenge)
                completionHandler(.useCredential, credential)
            }
    }
```

**Comment by kylehickinson** [comment]
@kythanh There's a few different way's you can do this. `WebViewStore` accepts handling a specific `WKWebView` that you pass through its initializer, so you could just create a `WKWebView` elsewhere, set up its delegates and hand it off to the `WebViewStore`. Otherwise you can always manually set the delegate's on the managed web view created by `WebViewStore` as well.
