### ISSUE TITLE
Reload page without cache

### ISSUE THREAD

**Issue by RyuuzakiJulio** [kylehickinson/SwiftUI-WebView#9]
Is there a way to reload a page and not using the cache?
Here is what's going on.

Server takes a while to detect credentials already sent, 
Server re-directs to login page,
After credentials are validated (on the backend),
WebView still shows login page. Reload or just Load still redirects to Login page. until closing the app and open it again.

**Comment by kylehickinson** [comment]
There are likely a few different ways you can approach this, but this issue is not related to this library which simply houses a `WKWebView`. This would happen if you were using just a regular `WKWebView` in a UIKit app as well. 

Maybe [clear the cache](https://gist.github.com/insidegui/4a5de215a920885e0f36294d51263a15) or change the [`cachePolicy`](https://developer.apple.com/documentation/foundation/nsurlrequest/1407944-cachepolicy) of the request you attempt to load?
